"""Typed request/response envelopes for the desktop frontend (R-C6).

The single source of truth for every shape that crosses the
frontend/backend boundary on the live-analysis path. ``scripts/gen_contract_ts.py``
renders these models into ``desktop/src/contract.ts``; ``tests/test_contract_parity.py``
fails if the generated file drifts, so the desktop can never redefine a shape
by hand and silently disagree with the engine.

These are presentation-layer contracts (they carry tables as JSON rows), not
the core ``Result`` contract in ``core/result.py`` (R7). Failures still travel
as ``ok: False`` plus diagnostics (R-C7) rather than as HTTP errors, so the
interface has one shape to render.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "CONTRACT_MODELS",
    "AnalyseRequest",
    "AnalyseResponse",
    "DiagnosticModel",
    "FigureOffer",
    "LiveSelection",
    "LiveStateModel",
    "ReadingModel",
    "RecommendedChart",
    "TableModel",
    "WarmRequest",
]

#: Every model the TS generator emits, in stable order. New envelopes join
#: this tuple; the generator and the parity test both read it, so adding a
#: model cannot quietly skip the contract.
CONTRACT_MODELS: tuple[type[BaseModel], ...] = ()


class _Contract(BaseModel):
    """Shared strictness: unknown fields are a caller bug, not a hint."""

    model_config = ConfigDict(extra="forbid")


class DiagnosticModel(_Contract):
    """One engine diagnostic, as the interface renders it (R-C7)."""

    severity: Literal["INFO", "WARNING", "ERROR"]
    code: str = Field(description="stable machine code, e.g. TOPIC_BAD_K")
    message: str = Field(description="plain words for the reader")


class RecommendedChart(_Contract):
    """A chart the engine suggests, from the same readout the reader sees."""

    kind: str
    x: str
    y: str
    agg: str = ""
    top_n: int | None = None
    question: str = ""
    why: str = ""


class FigureOffer(_Contract):
    """One of the tool's own figures this table can feed, by its question."""

    panel: str
    title: str
    question: str = ""
    shape: str = ""


class ReadingModel(_Contract):
    """The words half of a result: what the rows say and what to watch for.

    ``figures`` and ``table_first`` come from the tool's recipe
    (``core/viz/recipes.py``). A tool with either gets no generic
    ``recommended_charts``: those see only column types.
    """

    headline: str = ""
    observations: list[str] = Field(default_factory=list)
    cautions: list[str] = Field(default_factory=list)
    recommended_charts: list[RecommendedChart] = Field(default_factory=list)
    figures: list[FigureOffer] = Field(default_factory=list)
    table_first: str = Field(default="", description="why this result is read as a table; empty when a figure leads")


class TableModel(_Contract):
    """A result table in the shape the workbench draws (R-C6).

    Cells are strings on the wire: the table is for reading and charting, not
    for computation, and one stringy shape avoids the empty/NaN/null thicket.
    """

    columns: list[str]
    rows: list[dict[str, str]]
    total: int
    truncated: bool = False
    filtered_total: int | None = None
    offset: int | None = Field(default=None, description="row offset of this page; null when unpaginated")


class AnalyseRequest(_Contract):
    """One explicitly-run live analysis (R-C1).

    ``request_id`` is generated by the caller and echoed in the response so a
    superseded answer can be recognised and dropped (R-C2). ``snapshot_id``
    names the loaded corpus; a mismatch is refused (409), never silently
    answered (R-C4).
    """

    request_id: str = Field(min_length=8, max_length=64, description="client-generated; echoed back")
    tool: str = Field(min_length=1, max_length=64)
    params: dict[str, object] = Field(default_factory=dict)
    snapshot_id: str = Field(default="", max_length=128)


class AnalyseResponse(ReadingModel):
    """One live answer, or a clean failure (R-C7: never a hang)."""

    request_id: str = Field(description="echo of AnalyseRequest.request_id")
    tool: str
    ok: bool
    elapsed_ms: int = 0
    snapshot_id: str = ""
    path: str = ""
    table: TableModel | None = None
    panel: dict[str, object] | None = None
    #: Every figure this answer can draw (panel declarations), for the tabs.
    panels: list[dict[str, object]] = Field(default_factory=list)
    answer_id: str = Field(default="", description="cite this to redraw a figure with other settings")
    diagnostics: list[DiagnosticModel] = Field(default_factory=list)


class LiveSelection(_Contract):
    """What the warmed corpus covers, so a reading can say what it covers."""

    documents: int = 0
    words: int = 0
    names: list[str] = Field(default_factory=list)
    ids: list[str] = Field(default_factory=list)


class LiveStateModel(_Contract):
    """How warm a project's corpus is (mirrors desktop_backend/live.py)."""

    state: Literal["cold", "warming", "ready", "failed"]
    stage: str = ""
    error: str = ""
    documents: int = 0
    tokens: int = 0
    parsed: bool = False
    cached: bool = False
    source: Literal["", "parsed", "disk", "memory"] = ""
    parse_ms: int = 0
    selection: LiveSelection | None = None
    snapshot_id: str = ""
    parser: Literal["", "spacy", "stanza"] = ""


class WarmRequest(_Contract):
    """Ask the engine to read and parse the chosen documents (R-C4).

    The one slow step, and the one that may trigger heavy imports — which is
    why analyse never does (R-C5). ``selection`` is the caller's corpus scope;
    its shape is validated by ``desktop_backend.selection`` (an id list and a
    date window), not here, so the scope vocabulary has one owner.
    """

    parser: str = Field(default="spacy", max_length=32)
    selection: dict[str, object] | None = None


CONTRACT_MODELS = (
    DiagnosticModel,
    RecommendedChart,
    FigureOffer,
    ReadingModel,
    TableModel,
    AnalyseRequest,
    AnalyseResponse,
    LiveSelection,
    LiveStateModel,
    WarmRequest,
)
