"""Published model files. Generated by ``scripts/export_models.py``; do not edit.

``FILES[model_id][file_name] = (size_bytes, sha256)``. A model missing here
has not been exported and published yet.
"""

from __future__ import annotations

RELEASE = "models-1"

PRECISION: dict[str, str] = {
    "bert-base-uncased": "q8e4",
    "distilbert-sst2": "q8",
    "granite-embedding-english-r2": "q8e4",
    "qwen3-embedding-0.6b": "q8e4",
}

FILES: dict[str, dict[str, tuple[int, str]]] = {
    "bert-base-uncased": {
        "LICENSE": (11556, "5ad8c213095c573921d7388edf93f6a9f54490b8ebf3b165ae8ef1947cf70846"),
        "NOTICE": (440, "6cb972a6159d0d7c0bc34cfc8964967134c28d3afdbb8d9f4ef59b56f90d6a21"),
        "model.onnx": (104281111, "e18870c99ce8c26b556d159dba9301f34c4b4ee7f56bd0a194de1bfbb1dd372b"),
        "spec.json": (1369, "20a1207df2b82b38b1c05c47423680695fa472860b36a41a31fe30dd34725d04"),
        "tokenizer.json": (711551, "f17212c38517cfedc9306b57eeffbaf58c4976fcb42e5a87b405f36a7b9a9eb2"),
    },
    "distilbert-sst2": {
        "LICENSE": (11560, "3ddf9be5c28fe27dad143a5dc76eea25222ad1dd68934a047064e56ed2fa40c5"),
        "NOTICE": (448, "728af31f9b48284bee83354708842a8deecbbe987b34ac15cf5294fef7e4743b"),
        "model.onnx": (94313471, "ce64e5e10bd6a18cc8188047ac248b8cb742f67f818f039d941fd741b63ec577"),
        "spec.json": (1444, "db882269decdc5b3da20786a4eb38333fde86aebb905d6173a2c9f6ae3247dbb"),
        "tokenizer.json": (711551, "f17212c38517cfedc9306b57eeffbaf58c4976fcb42e5a87b405f36a7b9a9eb2"),
    },
    "granite-embedding-english-r2": {
        "LICENSE": (11560, "3ddf9be5c28fe27dad143a5dc76eea25222ad1dd68934a047064e56ed2fa40c5"),
        "NOTICE": (460, "89b4ddcc69fd1716be422f677e30fbf39e24459a8ec3872c2e2c07136a774da7"),
        "model.onnx": (139691740, "a26c6382313d187e537be1516fb29029194a7bc856e581912fbbc05fc8fd25f3"),
        "spec.json": (1063, "f8eafb5231420160f32104bfcd4eb88063eeea52f94b504f0cc4c83233583388"),
        "tokenizer.json": (3583387, "657af518d877b6422fa44277c008870520894bffcaea6490504ee426c57aa548"),
    },
    "qwen3-embedding-0.6b": {
        "LICENSE": (11560, "3ddf9be5c28fe27dad143a5dc76eea25222ad1dd68934a047064e56ed2fa40c5"),
        "NOTICE": (437, "8add6ec8453024142cf036e26ce0626e3e72e7d80c4716005e18fe036195c2b3"),
        "model.onnx": (557177145, "0dadfdb87719d9de9ae90c2348133af92d13cdb7ee5acad133cf73a558f303df"),
        "spec.json": (1188, "39caabccd5ccaf406296f2b6184e05b72352cd072221b11f4dd13816a137561b"),
        "tokenizer.json": (11423869, "c885aa3472589b15df8aaf95c2388c75b2542add53a49a7fb2d14117e0e5d2ab"),
    },
}
